// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Contraceptions = sequelize.define('contraceptions', {
    name: {
      type: DataTypes.STRING,
    },
    acronym: {
      type: DataTypes.STRING,
    },
    methodType: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    familyAcronym: {
      type: DataTypes.STRING,
    },
    practicalEfficiency: {
      type: DataTypes.INTEGER,
    },
    shortName: {
      type: DataTypes.STRING,
    },
    shortDescription: {
      type: DataTypes.STRING,
    },
    hormone: {
      type: DataTypes.BOOLEAN,
    },
    medicalConsultationRequired: {
      type: DataTypes.BOOLEAN,
    },
    photoFilename: {
      type: DataTypes.STRING,
    },
    pictoFilename: {
      type: DataTypes.STRING,
    },
    composition: {
      type: DataTypes.STRING,
    },
    presentation: {
      type: DataTypes.STRING,
    },
    usage: {
      type: DataTypes.STRING,
    },
    usageFrequency: {
      type: DataTypes.STRING,
    },
    istProtector: {
      type: DataTypes.STRING,
    },
    mentruations: {
      type: DataTypes.STRING,
    },
    refund: {
      type: DataTypes.STRING,
    },
    cost: {
      type: DataTypes.STRING,
    },
    tips: {
      type: DataTypes.STRING,
    },
    othersNames: {
      type: DataTypes.STRING,
    },
    howItWorks: {
      type: DataTypes.STRING,
    },
    secondaryEffect: {
      type: DataTypes.STRING,
    },
    sources: {
      type: DataTypes.STRING,
    },
    familyType: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'contraceptions',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Contraceptions.associate = (models) => {
  };

  return Contraceptions;
};
