// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SurveyPros = sequelize.define('survey_pros', {
    age: {
      type: DataTypes.INTEGER,
    },
    smoker: {
      type: DataTypes.BOOLEAN,
    },
    cigNumber: {
      type: DataTypes.INTEGER,
    },
    height: {
      type: DataTypes.INTEGER,
    },
    weight: {
      type: DataTypes.INTEGER,
    },
    familyDiseases: {
      type: DataTypes.STRING,
    },
    thromboEmbolicDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    heartDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    heartDiseasesWithPills: {
      type: DataTypes.BOOLEAN,
    },
    highEndocarditeRisk: {
      type: DataTypes.BOOLEAN,
    },
    arterialHypertension: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    diabetes: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    lupus: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    immobilisation: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    nbAbortion: {
      type: DataTypes.INTEGER,
    },
    nbMiscarriageSpontaneous: {
      type: DataTypes.INTEGER,
    },
    nbClassicBirths: {
      type: DataTypes.INTEGER,
    },
    nbCaesearanBirths: {
      type: DataTypes.INTEGER,
    },
    nbExtraUterinPregnancy: {
      type: DataTypes.INTEGER,
    },
    vaginalPenetration: {
      type: DataTypes.STRING,
    },
    postAbortumSituation: {
      type: DataTypes.STRING,
    },
    recurentMiscariageCheckup: {
      type: DataTypes.BOOLEAN,
    },
    deliveryUnderSixMonths: {
      type: DataTypes.STRING,
    },
    lastDeliveryOn: {
      type: DataTypes.DATE,
    },
    deliveryType: {
      type: DataTypes.STRING,
    },
    breastFeeding: {
      type: DataTypes.STRING,
    },
    exclusiveBreastFeeding: {
      type: DataTypes.STRING,
    },
    periodsBack: {
      type: DataTypes.STRING,
    },
    ovaryDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    uterusDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    vaginalDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    pregnancyPathology: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    mammaryPathology: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    mastopathyAtypia: {
      type: DataTypes.BOOLEAN,
    },
    ist: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    drugs: {
      type: DataTypes.STRING,
    },
    drugsTypes: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    enzymaticInhibitor: {
      type: DataTypes.STRING,
    },
    firstContraception: {
      type: DataTypes.BOOLEAN,
    },
    latexAllergy: {
      type: DataTypes.BOOLEAN,
    },
    easyReminder: {
      type: DataTypes.STRING,
    },
    desires: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    dyslipidemia: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    anemia: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    headeck: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    epilepsia: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    liverDiseases: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    acne: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    bariatricSurgery: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    cycles: {
      type: DataTypes.STRING,
    },
    menstruations: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    medicalsituation: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    gynecologicalsituation: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    dysthyroidie: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: Sequelize.literal('{}'),
    },
    menstruationsAbondance: {
      type: DataTypes.INTEGER,
    },
    menstruationsDuration: {
      type: DataTypes.INTEGER,
    },
    menstruationsPain: {
      type: DataTypes.STRING,
    },
    menstruationsSpotting: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'survey_pros',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  SurveyPros.associate = (models) => {
  };

  return SurveyPros;
};
